#!/usr/bin/env bash
# numbers from 1 to
# printing "bad luck from China" for the 4th iteration
# printing "bad luck from Japan" for the 9th iteration
# printing "bad luck from Italy" for the 17th loop iteration

start=1

while [ $start -le 20 ]
do
	echo "$start"
	case $start in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( start++ ))
done
