#!/usr/bin/env bash
# This script connects to the server using SSH with a private key

# Set the SSH private key file path
PRIVATE_KEY="~/.ssh/school"

# Set the server IP address
SERVER_IP="3.85.148.122"

# SSH connection using the provided private key and username
ssh -i "$PRIVATE_KEY" ubuntu@"$SERVER_IP"
